<?php 
include('header.php');
include ('connection.php');
 ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment</title>
    <link rel="stylesheet" type="text/css" href="paystyle.css">
</head>
<body>
<form method="POST">
  <div class="form-group">
    <label for="card-number">Card Number</label>
    <input type="text" id="card-number" name="card-number" placeholder="xxxx xxxx xxxx xxxx" required>
  </div>

  <div class="form-group">
    <label for="expiry-date">Expiry Date</label>
    <input type="month" id="expiry-date" name="expiry-date" placeholder="MM / YY" required>
  </div>

  <div class="form-group">
    <label for="cvv">CVV</label>
    <input type="number" id="cvv" name="cvv" placeholder="123" required>
  </div>

  <div class="form-group">
    <label for="name-on-card">Name on Card</label>
    <input type="text" id="name-on-card" name="name-on-card" placeholder="John Doe" required>
  </div>

  <button type="submit" name="pay">Submit Payment</button>

</form>

<!-- subscription payment -->
<?php

// Retrieve patient data from the database
$e = $_SESSION['name'];
$pid = $_SESSION['pid'];

if (!isset($_SESSION['name'])) {
  header("Location: login.php");
  exit();
}

if (isset($_POST['subscribe'])) {

  $card_number = $_POST['Card_no'];
  $expiry_date = $_POST['expiry_date'];
  $cvv = $_POST['cvv'];
  $name_on_card = $_POST['name'];
  $paydate = date('Y-m-d');   //date function generate the current date
  $amount = '1500';

  $sql = "INSERT INTO payment (Card_no, expiry_date, cvv, name,	paydate, Total_Value)
  VALUES ('$card_number', ' $expiry_date', '$cvv', '  $name_on_card', '$paydate', '$amount')";

if (mysqli_query($con, $sql)) {

  $last_id = mysqli_insert_id($con); // get the ID generated by the previous INSERT query
   
//     echo ' <div class="alert-success"> 
//     <span class="closebtn" onclick="this.parentElement.style.display="none";">&times;</span> 
// <strong>Success!</strong> Payment Completed Successfully.
// </div>';

// Retrieve payment date from payment table
$query = "SELECT paydate FROM payment WHERE Payment_ID= $last_id";
$result = mysqli_query($con, $query);
$row = mysqli_fetch_assoc($result);
$paydate = $row['paydate'];


// Calculate date after a month
$subdate = date('Y-m-d', strtotime('+1 month', strtotime($paydate)));

// Check if current date is before expiry date
if (date('Y-m-d') <= $subdate) {
  // Payment is still valid
  $status = 'active';
} else {
  // Payment has expired
  $status = 'expired';
}

// Insert subscription date into subscription table
$stmt = "INSERT INTO sub_plan (Start_Date,End_Date,status) VALUES ('$paydate' , '$subdate' , '$status' )";
mysqli_query($con, $stmt);


$squery = "SELECT Sub_ID  FROM patients WHERE Email = $e";
$r = mysqli_query($con, $squery); 
$row = mysqli_fetch_assoc($r);
$subid = $row['Sub_ID'];

// The user is logged in, allow them to book the event
if(isset($_GET['eventid'])){
    $eventid = $_GET['eventid'];

    // $sql = "SELECT sub_plan.* , patients.*
    // FROM sub_plan 
    // FULL JOIN patients
    // ON sub_plan.Sub_ID = patients.Sub_ID
    // WHERE patients.Email = '$e' AND sub_plan.Event_ID NOT NULL ";
    $sql="SELECT Event_ID FROM sub_plan
    WHERE Event_ID IS NOT NULL AND Sub_ID =$subid ";

$result = mysqli_query($con, $sql);

if (mysqli_num_rows($result) > 0) {
    // User has already booked an event
    echo 'You have already booked an event.';
} else {
   

    $sql="INSERT INTO sub_plan (Event_ID) VALUES ('$eventid')";
    $result = mysqli_query($con, $sql);
    if ($result) {
        // User has booked an event
        echo 'You have booked an event.';
    }
}
}

if(isset($_GET['bookid'])){
    $eventid = $_GET['bookid'];

    $sql = "SELECT sub_plan.* , patients.*
    FROM sub_plan 
    FULL JOIN patients
    ON sub_plan.Sub_ID = patients.Sub_ID
    WHERE Event_ID NOT NULL";
$result = mysqli_query($con, $sql);

if (mysqli_num_rows($result) > 0) {
    // User has already booked an event
    echo 'You have already booked an event.';
} else {

    $sql="INSERT INTO sub_plan (Book_ID) VALUES ('$eventid')";
}
}

if(isset($_GET['groupid'])){
    $eventid = $_GET['groupid'];

    $sql = "SELECT event_id FROM sub_plan WHERE user_id = $user_id";
$result = mysqli_query($con, $sql);

if (mysqli_num_rows($result) > 0) {
    // User has already booked an event
    echo 'You have already booked an event.';
} else {

    $sql="INSERT INTO sub_plan (Group_ID) VALUES ('$eventid')";
}
}

} else { 

   echo '<div class="alert"> 
   <span class="closebtn" onclick="this.parentElement.style.display="none";">&times;</span> 
<strong>Error!</strong> Payment Failed.
</div>';
    
mysqli_close($con);
}
}

?>
  
</body>
</html>

