<?php
include('connection.php');
include('logform.php');

// Retrieve patient data from the database
$e = $_SESSION['name'];

if (!isset($_SESSION['name'])) {
    header("Location: login.php");
    exit();
}

//subscription payment
if (isset($_POST['pay'])) {

    $card_number = $_POST['Card_no'];
    $hashed_card_number = hash('sha256', $card_number);
    $expiry_date = $_POST['expiry_date'];
    $expiry_date_formatted = date('Y-m-1', strtotime($expiry_date));
    $cvv = $_POST['cvv'];
    $name_on_card = $_POST['name'];
    $paydate = date('Y-m-d');   //date function generate the current date
    $amount = '1500';
    $expdate = date('Y-m-d', strtotime('+1 month', strtotime($paydate)));  //calculate expiry-date of sub plan
    // Check if current date is before expiry date
    if (date('Y-m-d') <= $expdate) {
        // Payment is still valid
        $status = 'active';
    } else {
        // Payment has expired
        $status = 'expired';
    }

    $query = "INSERT INTO sub_plan (Start_Date,	End_Date, status)
    VALUES ('$paydate', '$expdate', '$status')";

    if (mysqli_query($con, $query)) {

        $last_id = mysqli_insert_id($con); // get the ID generated by the previous INSERT query

        $sql = "INSERT INTO payment (Card_no, expiry_date, cvv, name,	paydate, Total_Value, Sub_ID)
    VALUES ('$hashed_card_number', '$expiry_date_formatted' , '$cvv', '$name_on_card', '$paydate', '$amount', '$last_id')";

        if (mysqli_query($con, $sql)) {

            $sq = "UPDATE `patients` SET `Sub_ID` = '$last_id' WHERE Email='$e'";
        
                if (mysqli_query($con, $sq)) {
                echo "<script>alert('Payment Successful')</script>";
                echo "<script>window.location.href = 'index.php'; </script>";
            } else {
                echo "<script>alert('Payment Fail')</script>";
            }
        }
    }
}

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment</title>
    <link rel="stylesheet" type="text/css" href="paystyle.css">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="./Header-Footer/headerfooter.css">
</head>

<body>
<?php include ('header.php')?>
<div class='form-container'>
    <form method="POST">
        <div class="form-group">
            <label for="card-number">Card Number</label>
            <input type="text" id="card-number" name="Card_no" placeholder="xxxx xxxx xxxx xxxx" required>
        </div>

        <div class="form-group">
            <label for="expiry-date">Expiry Date</label>
            <input type="month" id="expiry-date" name="expiry_date" placeholder="MM / YY" required>
        </div>

        <div class="form-group">
            <label for="cvv">CVV</label>
            <input type="number" id="cvv" name="cvv" placeholder="123" required>
        </div>

        <div class="form-group">
            <label for="name-on-card">Name on Card</label>
            <input type="text" id="name-on-card" name="name" placeholder="John Doe" required>
        </div>

        <button type="submit" name="pay">Submit Payment</button>

    </form>
</div>
</body>

</html>